### ISSUE TITLE
Bot doesn't respond to pings when no reason is given

### ISSUE THREAD

**Issue by pewpasta** [MihaiCit/Afk-Bot#1]
The bot doesn't respond to pings when no reason is given during the !afk command.
It only responds to pings when a reason is given during the !afk command

**Comment by kkMihai** [comment]
This is might be your problem bc i tested and for me is respond, but i will see

**Comment by pewpasta** [comment]
It was exactly the same code. I just changed the token.

Bot responds to pings only if reason was given in the AFK command.

Here's what happens tho 
![hOQM0nY0xK](https://user-images.githubusercontent.com/67459484/106457201-a03a5380-64b4-11eb-90a0-cf6b7fc41faa.gif)

In the first case, where I didn't put any reason. The bot didn't respond to any pings and didn't show any message when it came back.
In the second case where the reason was put in the AFK command, the bot responded to pings.

**Comment by kkMihai** [comment]
hmmm, i will fix it

**Comment by kkMihai** [comment]
Okay so i fixed the problem it's was at the command `afk` now should work i test it, if there is another problem let me know
