### ISSUE TITLE
Suggestion: Show the duration of afk when pinged

### ISSUE THREAD

**Issue by pewpasta** [MihaiCit/Afk-Bot#2]
Show the duration of the mentioned person's afk, like Dyno bot lol
![Screenshot_20210201-115546_Discord](https://user-images.githubusercontent.com/67459484/106422419-8f71e980-6484-11eb-90d9-004dd2457146.jpg)

**Comment by kkMihai** [comment]
That's a cool idea thanks maybe i will add it :D
