### ISSUE TITLE
Emojis don't embed in the bot's afk message

### ISSUE THREAD

**Issue by iyeetchildren** [MihaiCit/Afk-Bot#3]
the emoji doesn't embed, and it just shows the emoji name within semicolons

**Comment by MihaiCit** [comment]
can u send a screenshot?

**Comment by MihaiCit** [comment]
Oh i know why it's bc u need to learn discord.js idiot
`<:emojiname:emoji_iD>

**Comment by iyeetchildren** [comment]
Ngl, I don't know discord.js much. But this only happens with Nitro Emojis. Server emojis work fine 
![Screenshot_1](https://user-images.githubusercontent.com/78363618/106472540-c8cc4880-64c8-11eb-8ddc-6c2d2bfdb92e.png)

**Comment by kkMihai** [comment]
Ohhhh me more stupid, you wanted to put emoji in the afk message, yea this only works with server emojis

**Comment by kkMihai** [comment]
Cya
